### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by turtton** [turtton/myvim.nix#1]
- [ ] fix copilot-cmp
- [ ] add newfile button on top page
- [x] fix split window key
- [x] add lsp keybinds
- [x] try Kotlin language server
- [ ] keep file tree opening state
- [x] add Github Actions completion

**Comment by turtton** [comment]
https://www.lazyvim.org/extras/coding/copilot
↑not work for me😭😭😭
